##
# @file
#
# Makefile for the Demo C++ Framework project
#     - Borland C++ compiler (definitions).
#
# @author Emil Maskovsky
#


############################
#     Compiler options     #
############################

# Suffix of object file names.
# (cannot be empty)
OBJ_SFX := obj


# ANSI-C compiler settings.

# The compiler executable.
CC := bcc32

# The compiler global flags.
# (used standardized name CFLAFS, which can be
# overridden on the make command line)
CFLAGS := -q -d

# Output name flag.
CC_OUT := -o
# Compile-only flag.
CC_COMPILE_ONLY := -c
# Macro definition flag.
CC_DEFINE := -D
# Include directory flag.
CC_INCLUDE := -I

# Flags for different build configurations.
CFLAGS_UNICODE := -WU
CFLAGS_DEBUG := -w -Od -v
CFLAGS_RELEASE := -w- -O2
CFLAGS_LIB := -WC
CFLAGS_LIBMT := -WM
CFLAGS_DLL := -WD


# C++ compiler settings.

# The compiler executable.
CXX := $(CC)

# The compiler global flags.
# (used standardized name CXXFLAGS, which can be
# overridden on the make command line)
CXXFLAGS := $(CFLAGS) -x -xd -RT

# Output name flag.
CXX_OUT := $(CC_OUT)
# Compile-only flag.
CXX_COMPILE_ONLY := $(CC_COMPILE_ONLY)
# Macro definition flag.
CXX_DEFINE := $(CC_DEFINE)
# Include directory flag.
CXX_INCLUDE := $(CC_INCLUDE)

# Flags for different build configurations.
CXXFLAGS_UNICODE := $(CFLAGS_UNICODE)
CXXFLAGS_DEBUG := $(CFLAGS_DEBUG)
CXXFLAGS_RELEASE := $(CFLAGS_RELEASE)
CXXFLAGS_LIB := $(CFLAGS_LIB)
CXXFLAGS_LIBMT := $(CFLAGS_LIBMT)
CXXFLAGS_DLL := $(CFLAGS_DLL)


# Resource compiler settings.

# The compiler executable.
RC := brcc32

# Suffix of compiled resource files.
# (cannot be empty, if RC defined)
RES_SFX := res

# The compiler global flags.
# (used standardized name RCFLAGS, which can be
# overridden on the make command line)
RCFLAGS := -32 -iC:\SW\Borland\Bcc55\include

# Output name flag.
RC_OUT := -fo

# Macro definition flag.
RC_DEFINE := -d
# Include directory flag.
RC_INCLUDE := -i


##########################
#     Linker options     #
##########################

# The linker global flags.
# (used standardized name LDFLAGS, which can be
# overridden on the make command line)
LDFLAGS := /q /x

# Suffix of object libraries.
# (cannot be empty)
LIB_SFX := lib


# C++ linker settings.

# The linker executable.
LNKC := ilink32

# The linker global flags.
# (includes standard name LDFLAGS, which can be
# overridden on the make command line)
LNKC_FLAGS := $(LDFLAGS) /Tpe /ap

# Output name flag.
LNKC_OUT := , 
LNKC_LIB_START := ,, cw32i.lib 
LNKC_RES_START := ,, 

# Flags for different build configurations.
LNKC_FLAGS_DEBUG := /v /w
LNKC_FLAGS_RELEASE :=

LNKC_LIB_SFX := .$(LIB_SFX)


# C++ librarian compiler settings.

# The librarian executable.
LIBC := tlib

# The librarian global flags.
LIBC_FLAGS := /P4096 /a

# Output name flag.
LIBC_OUT := 


# C++ dynamic library linker settings.

# The linker executable.
DLLC := $(LNKC)

# The linker global flags.
# (includes standard name LDFLAGS, which can be
# overridden on the make command line)
DLLC_FLAGS := $(LDFLAGS) /Tpd

# Output name flag.
DLLC_OUT := $(LNKC_OUT)
DLLC_LIB_START := $(LNKC_LIB_START)
DLLC_RES_START := $(LNKC_RES_START)

# Flags for different build configurations.
DLLC_FLAGS_DEBUG := $(LNKC_FLAGS_DEBUG)
DLLC_FLAGS_RELEASE := $(LNKC_FLAGS_RELEASE)

# Tool for creating the import library from the DLL.
DLLC_IMPLIB := implib
DLLC_IMPLIB_FLAGS := 
DLLC_IMPLIB_OUT := 


# Addditional clean masks for 'clean...' targets.
MXCPP_CLEAN_MASK = *.bak
MXCPP_CLEAN_MASK_DEBUG = 
MXCPP_CLEAN_MASK_TEST = $(1)*.tds
MXCPP_CLEAN_MASK_TEST_DEBUG = 

# Addditional clean masks for 'cleanall...' targets.
MXCPP_CLEANALL_MASK_DLL = $(2:.dll=.lib) $(2:.dll=.tds)
MXCPP_CLEANALL_MASK_DLL_DEBUG = 


# Include parent definitions.
include ../system.ini

# EOF #
